<Project>
    <PropertyGroup>
        <Version>0.2.0</Version>
        <Authors>JT</Authors>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <Copyright>JT 2026</Copyright>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>schematic;entitlements;feature-flags;$(PackageTags)</PackageTags>
    </PropertyGroup>
    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DotNet.ReproducibleBuilds">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>
