<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Alba" />
      <PackageReference Include="Shouldly" />
      <PackageReference Include="TUnit" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Schematic.AspNetCore.TestApp\Schematic.AspNetCore.TestApp.csproj" />
      <ProjectReference Include="..\Schematic.AspNetCore\Schematic.AspNetCore.csproj" />
      <ProjectReference Include="..\Schematic.Extensions.AI\Schematic.Extensions.AI.csproj" />
      <ProjectReference Include="..\Schematic.Extensions.Quartz\Schematic.Extensions.Quartz.csproj" />
    </ItemGroup>

</Project>
